# Alembic script.py.mako — template for auto-generated revisions
"""add runner_state table for host-owned persistent state

Revision ID: 6dfd3dd7f0c7
Revises: 58846a8d7a81
Create Date: 2026-05-23 19:49:08.529110
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '6dfd3dd7f0c7'
down_revision = '58846a8d7a81'
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    return table_name in sa.inspect(op.get_bind()).get_table_names()


def _index_exists(table_name: str, index_name: str) -> bool:
    return index_name in {index['name'] for index in sa.inspect(op.get_bind()).get_indexes(table_name)}


def _create_index_if_missing(table_name: str, index_name: str, columns: list[str], *, unique: bool = False) -> None:
    if not _table_exists(table_name) or _index_exists(table_name, index_name):
        return
    with op.batch_alter_table(table_name, schema=None) as batch_op:
        batch_op.create_index(index_name, columns, unique=unique)


def _drop_index_if_exists(table_name: str, index_name: str) -> None:
    if not _table_exists(table_name) or not _index_exists(table_name, index_name):
        return
    with op.batch_alter_table(table_name, schema=None) as batch_op:
        batch_op.drop_index(index_name)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('agent_runner_state'):
        op.create_table(
            'agent_runner_state',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('runner_id', sa.String(length=255), nullable=False),
            sa.Column('binding_identity', sa.String(length=255), nullable=False),
            sa.Column('scope', sa.String(length=50), nullable=False),
            sa.Column('scope_key', sa.String(length=512), nullable=False),
            sa.Column('state_key', sa.String(length=255), nullable=False),
            sa.Column('value_json', sa.Text(), nullable=True),
            sa.Column('bot_id', sa.String(length=255), nullable=True),
            sa.Column('workspace_id', sa.String(length=255), nullable=True),
            sa.Column('conversation_id', sa.String(length=255), nullable=True),
            sa.Column('thread_id', sa.String(length=255), nullable=True),
            sa.Column('actor_type', sa.String(length=50), nullable=True),
            sa.Column('actor_id', sa.String(length=255), nullable=True),
            sa.Column('subject_type', sa.String(length=50), nullable=True),
            sa.Column('subject_id', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('scope_key', 'state_key', name='uq_agent_runner_state_scope_key_state_key'),
        )
    _create_index_if_missing('agent_runner_state', 'ix_agent_runner_state_actor_id', ['actor_id'])
    _create_index_if_missing('agent_runner_state', 'ix_agent_runner_state_binding_identity', ['binding_identity'])
    _create_index_if_missing('agent_runner_state', 'ix_agent_runner_state_bot_id', ['bot_id'])
    _create_index_if_missing('agent_runner_state', 'ix_agent_runner_state_conversation_id', ['conversation_id'])
    _create_index_if_missing(
        'agent_runner_state',
        'ix_agent_runner_state_runner_binding',
        ['runner_id', 'binding_identity'],
    )
    _create_index_if_missing('agent_runner_state', 'ix_agent_runner_state_runner_id', ['runner_id'])
    _create_index_if_missing('agent_runner_state', 'ix_agent_runner_state_scope', ['scope'])
    _create_index_if_missing('agent_runner_state', 'ix_agent_runner_state_scope_key_lookup', ['scope_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_scope_key_lookup')
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_scope')
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_runner_id')
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_runner_binding')
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_conversation_id')
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_bot_id')
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_binding_identity')
    _drop_index_if_exists('agent_runner_state', 'ix_agent_runner_state_actor_id')

    if _table_exists('agent_runner_state'):
        op.drop_table('agent_runner_state')
    # ### end Alembic commands ###
