apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: iflytek-chat-completions
  label:
    en_US: iFlytek Spark
    zh_Hans: 讯飞星火
  icon: iflytek.svg
spec:
  litellm_provider: openai
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://spark-api-open.xf-yun.com/v1
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  alias: "iflytek 讯飞 科大讯飞 星火 spark xinghuo xunfei 讯飞星火"
  support_type:
  - llm
  - text-embedding
  - rerank
  provider_category: manufacturer
