apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: mimo-chat-completions
  label:
    en_US: Xiaomi MiMo
    zh_Hans: 小米 MiMo
  icon: mimo.svg
spec:
  litellm_provider: openai
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://api.xiaomimimo.com/v1
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  alias: "mimo MiMo 小米 xiaomi 小米大模型 xiaomi-mimo"
  support_type:
  - llm
  - text-embedding
  - rerank
  provider_category: manufacturer
