apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: mistral-chat-completions
  label:
    en_US: Mistral AI
    zh_Hans: Mistral AI
  icon: mistral.svg
spec:
  litellm_provider: mistral
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://api.mistral.ai/v1
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  alias: "mistral Mistral 米斯特拉尔 mixtral codestral mistral-embed le-chat"
  support_type:
  - llm
  - text-embedding
  provider_category: manufacturer
