apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: qiniu-chat-completions
  label:
    en_US: Qiniu
    zh_Hans: 七牛云
  icon: qiniu.svg
spec:
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://api.qnaigc.com/v1
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  support_type:
  - llm
  provider_category: maas
execution:
  python:
    path: ./qiniuchatcmpl.py
    attr: QiniuChatCompletions
