apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: tencent-chat-completions
  label:
    en_US: Tencent Hunyuan
    zh_Hans: 腾讯混元
  icon: tencent.svg
spec:
  litellm_provider: openai
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://hunyuan.tencentcloudapi.com/v1
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  alias: "tencent 腾讯 腾讯云 hunyuan 混元 tencent-cloud txcloud 元宝"
  support_type:
  - llm
  - text-embedding
  - rerank
  provider_category: manufacturer
