apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: yi-chat-completions
  label:
    en_US: 01.AI Yi
    zh_Hans: 零一万物
  icon: yi.svg
spec:
  litellm_provider: openai
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://api.lingyiwanwu.com/v1
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  alias: "yi 零一 零一万物 零一万 lingyiwanwu 01 01.ai 万智 yi-large yi-lightning embedding"
  support_type:
  - llm
  - text-embedding
  - rerank
  provider_category: manufacturer
