apiVersion: v1
kind: LLMAPIRequester
metadata:
  name: zhipuai-chat-completions
  label:
    en_US: ZhipuAI
    zh_Hans: 智谱 AI
  icon: zhipuai.svg
spec:
  litellm_provider: openai
  config:
  - name: base_url
    label:
      en_US: Base URL
      zh_Hans: 基础 URL
    type: string
    required: true
    default: https://open.bigmodel.cn/api/paas/v4
  - name: timeout
    label:
      en_US: Timeout
      zh_Hans: 超时时间
    type: integer
    required: true
    default: 120
  alias: "zhipu zhipuai 智谱 智谱AI 智谱清言 glm GLM chatglm 清言 bigmodel embedding-3 rerank"
  support_type:
  - llm
  - text-embedding
  - rerank
  provider_category: manufacturer
execution:
  python:
    path: ./zhipuaichatcmpl.py
    attr: ZhipuAIChatCompletions
