apiVersion: v1
kind: MessagePlatformAdapter
metadata:
  name: wecomcs
  label:
    en_US: WeComCustomerService
    zh_Hans: 企业微信客服
    zh_Hant: 企業微信客服
  description:
    en_US: WeComCSAdapter
    zh_Hans: 企业微信对外客服机器人，需要公网地址以接收消息推送，请查看文档了解使用方式
    zh_Hant: 企業微信對外客服機器人，需要公網地址以接收訊息推送，請查看文件了解使用方式
  icon: wecom.png
spec:
  categories:
    - china
  config:
    - name: webhook_url
      label:
        en_US: Webhook Callback URL
        zh_Hans: Webhook 回调地址
        zh_Hant: Webhook 回調地址
      description:
        en_US: Copy this URL and paste it into your WeCom Customer Service webhook configuration
        zh_Hans: 复制此地址并粘贴到企业微信客服的 Webhook 配置中
        zh_Hant: 複製此地址並貼到企業微信客服的 Webhook 設定中
      type: webhook-url
      required: false
      default: ""
    - name: corpid
      label:
        en_US: Corpid
        zh_Hans: 企业ID
        zh_Hant: 企業ID
      type: string
      required: true
      default: ""
    - name: secret
      label:
        en_US: Secret
        zh_Hans: 密钥
        zh_Hant: 密鑰
      type: string
      required: true
      default: ""
    - name: token
      label:
        en_US: Token
        zh_Hans: 令牌
        zh_Hant: 令牌
      type: string
      required: true
      default: ""
    - name: EncodingAESKey
      label:
        en_US: EncodingAESKey
        zh_Hans: 消息加解密密钥
        zh_Hant: 訊息加解密密鑰
      type: string
      required: true
      default: ""
    - name: api_base_url
      label:
        en_US: API Base URL
        zh_Hans: API 基础 URL
        zh_Hant: API 基礎 URL
      description:
        en_US: API Base URL, used for accessing the WeCom API. If you are deploying in an internal network environment and accessing the WeCom Customer Service API through a reverse proxy, please fill in this item according to the documentation.
        zh_Hans: 可选，若您部署在内网环境并通过反向代理访问企业微信 API，可根据文档修改此项
        zh_Hant: 可選，若您部署在內網環境並透過反向代理存取企業微信 API，可根據文件修改此項
      type: string
      required: false
      default: "https://qyapi.weixin.qq.com/cgi-bin"
execution:
  python:
    path: ./wecomcs.py
    attr: WecomCSAdapter