name: 漏洞反馈
description: 报错或漏洞请使用这个模板创建，不使用此模板创建的异常、漏洞相关issue将被直接关闭。由于自己操作不当/不甚了解所用技术栈引起的网络连接问题恕无法解决，请勿提 issue。容器间网络连接问题，参考文档 https://docs.langbot.app/deploy/network-details.html  
title: "[Bug]: "
labels: ["bug?"]
body:
  - type: dropdown
    attributes:
      label: 消息平台适配器
      description: "接入的消息平台类型"
      options:
        - 其他（或暂未使用）
        - Nakuru（go-cqhttp）
        - aiocqhttp（使用 OneBot 协议接入的）
        - qq-botpy（QQ官方API WebSocket）
        - qqofficial（QQ官方API Webhook）
        - lark（飞书）
        - wecom（企业微信）
        - gewechat（个人微信）
        - discord
    validations:
      required: true
  - type: input
    attributes:
      label: 运行环境
      description: LangBot 版本、操作系统、系统架构、**Python版本**、**主机地理位置**
      placeholder: 例如：v3.3.0、CentOS x64 Python 3.10.3、Docker 的系统直接写 Docker 就行
    validations:
      required: true
  - type: textarea
    attributes:
      label: 异常情况
      description: 完整描述异常情况，什么时候发生的、发生了什么。**请附带日志信息。** 
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤
      description: 如何重现这个问题，越详细越好；请贴上所有相关的配置文件和元数据文件（注意隐去敏感信息）
    validations:
      required: true
  - type: textarea
    attributes:
      label: 启用的插件
      description: 有些情况可能和插件功能有关，建议提供插件启用情况。可以使用`!plugin`命令查看已启用的插件
    validations:
      required: false
