export default {
  complete: 'Done',
  checkingPlugin: 'Check plugin',
  preparingPlugin: 'Prepare installation',
  installDetails: 'Installation details',
  stageProgress: 'Stage progress',
  downloaded: 'Downloaded {{size}}',
  processed: 'Processed {{completed}} / {{total}} pipelines',
  installErrors: {
    plugin_version_unavailable:
      'The required plugin version is not available in the marketplace. Retry after it is published, or migrate data only.',
    plugin_download_timeout:
      'Plugin download timed out. Check the network and retry.',
    plugin_marketplace_unavailable:
      'The marketplace could not serve the plugin package. Retry later.',
    plugin_download_failed:
      'Could not download the plugin. Check the network and retry.',
    dependency_prepare_failed:
      'Plugin dependencies could not be installed. Check the runtime environment and retry.',
    plugin_launch_failed:
      'The plugin could not start. Check the runtime environment and retry.',
  },
  autoDescription:
    'Legacy runners are now plugins. Migrate all pipelines while keeping your settings. Original configurations are backed up; conversations start fresh.',
  viewPipelines: 'View pipelines',
  autoInstall: 'Install plugins and migrate',
  dataOnly: 'Migrate data only',
  dataOnlyHint:
    'For offline or private networks. Install the corresponding runner plugins yourself after migration.',
  installing: 'Installing required plugins…',
  migrating: 'Migrating pipelines…',
  summary: '{{migrated}} migrated; {{remaining}} need attention.',
  installFailed:
    'Plugin installation failed. Expand the details to see the failed stage, then retry or migrate data only.',

  activationRetryHint:
    'After checking the runtime, refresh, select this pipeline and confirm to retry activation only. Its saved configuration will not be migrated again.',
  details: 'Migration details',
  notices: {
    runtimeUnavailable:
      'The plugin runtime is disconnected. Restore the connection and retry, or migrate data only.',
    executionFailed: 'Migration failed. Check the server logs and retry.',
    pluginRequired:
      'Install or enable the runner plugin shown above, then refresh the preview.',
    legacyArchive:
      'The active configuration will contain only the selected runner. All original runner settings, including inactive ones, are kept in the migration backup.',
    contextDefaults:
      'History will use the new context budget and summarization defaults instead of a fixed round limit.',
    modelReasoning:
      'Per-model reasoning settings are preserved and applied by the host.',
    serialTools: 'Tool calls remain sequential after migration.',
    retrievalDefaults:
      'Retrieval uses the new top-k and result limits. Review them after migration.',
    boxReset:
      'Sandbox reuse settings are preserved. Existing container state is not migrated; new sandboxes follow the same reuse rules.',
    persistentHistory:
      'New conversations use persistent, isolated history. Existing remote history is not imported.',
    tweaksDefault: 'Langflow tweaks default to an empty object.',
    timeoutDefault: 'Dify uses a 30-second request timeout by default.',
    historyReset:
      'Existing conversation history and session identifiers are not transferred. New conversations start after migration.',
    sessionTitle: 'New WeKnora sessions use titles generated by the plugin.',
    aliasRepaired: 'The old field name is mapped to its supported replacement.',
    nullDefault: 'This empty value uses the new plugin default.',
    outputPolicy:
      'The existing reasoning-output visibility setting is preserved.',
    filteredVariables:
      'Only supported variables are transferred; reserved variables are supplied by the conversation context.',
    identityPreserved: 'The provider user identity keeps its legacy source.',
    newDefaults:
      'New plugin options use their documented defaults; existing supported values are retained.',
    externalState:
      'Complete or cancel pending remote interactions before migration; their live state is not transferred.',
    pluginVersion:
      'Install the required plugin version, then refresh. Older versions are not compatible with this migration.',
    schemaChanged:
      'The installed runner configuration does not match the migration target. Check the plugin version and refresh.',
    runnerExcluded:
      'This pipeline excludes the required runner plugin. Update its extension settings first.',
    boxTemplateInvalid:
      'Invalid sandbox reuse template. Use {variable_name}; positional fields, format conversions and attribute access are not supported.',
    pendingInteraction:
      'A conversation is waiting for input. Complete or cancel it before migration.',
  },
  title: 'Pipeline migration',
  description:
    'Select pipelines to migrate. Original settings are backed up; conversations start fresh after migration.',
  detected: '{{count}} pipelines need migration review.',
  review: 'Review migration',
  readOnly: 'Only workspace managers can migrate pipelines.',
  previewError: 'Preview unavailable. Refresh to check again.',
  submitting: 'Submitting selected pipelines…',
  running:
    'Migration is running. Closing this dialog does not cancel the task.',
  finished: 'Task finished. Check each pipeline result below.',
  failed: 'Task failed. Check each pipeline result below.',
  lost: 'Task observation lost. Its outcome is unknown; refresh the preview before any further action.',
  requestError:
    'Request not completed. Refresh the preview before selecting again.',
  warningFallback: 'Review this setting before migration.',
  blockerFallback:
    'This setting or runtime condition cannot be migrated safely. Resolve it and refresh the preview.',
  changedFields: 'Changed fields',
  activationHint:
    'Configuration was saved, but activation is pending. Ask a workspace administrator to check runtime availability, then refresh. Do not rerun migration blindly.',
  pluginHint:
    'Missing a plugin? Install or enable its runner in Extensions, then refresh the preview.',
  extensions: 'Open Extensions',
  results: 'Per-pipeline results',
  selection: '{{count}} selected (maximum 50)',
  confirm: 'I confirm migration of the selected pipelines.',
  refresh: 'Refresh preview',
  execute: 'Migrate selected',
  legacyGate:
    'Legacy configuration is read-only until migration. Save and debug are unavailable to prevent implicit conversion.',
  states: {
    ready: 'Ready',
    needs_plugin: 'Plugin required',
    blocked: 'Blocked',
    already_current: 'Already current',
    not_legacy: 'Not legacy',
    activation_pending: 'Activation pending',
    pending: 'Pending',
    migrated: 'Migrated',
    stale: 'Stale preview',
    failed: 'Failed',
  },
};
