export default {
  activationRetryHint:
    'After checking the runtime, refresh, select this pipeline and confirm to retry activation only. Its saved configuration will not be migrated again.',
  notices: {
    legacyArchive:
      'The active configuration will contain only the selected runner. All original runner settings, including inactive ones, are kept in the migration backup.',
    contextDefaults:
      'History will use the new context budget and summarization defaults instead of a fixed round limit.',
    modelReasoning:
      'Per-model reasoning settings are preserved and applied by the host.',
    serialTools: 'Tool calls remain sequential after migration.',
    retrievalDefaults:
      'Retrieval uses the new top-k and result limits. Review them after migration.',
    boxReset:
      'Existing Box session state is not transferred; a new isolated session will be created.',
    persistentHistory:
      'New conversations use persistent, isolated history. Existing remote history is not imported.',
    tweaksDefault: 'Langflow tweaks default to an empty object.',
    timeoutDefault: 'Dify uses a 30-second request timeout by default.',
    historyReset:
      'Existing conversation history and session identifiers are not transferred. New conversations start after migration.',
    sessionTitle: 'New WeKnora sessions use titles generated by the plugin.',
    aliasRepaired: 'The old field name is mapped to its supported replacement.',
    nullDefault: 'This empty value uses the new plugin default.',
    outputPolicy:
      'The existing reasoning-output visibility setting is preserved.',
    filteredVariables:
      'Only supported variables are transferred; reserved variables are supplied by the conversation context.',
    identityPreserved: 'The provider user identity keeps its legacy source.',
    newDefaults:
      'New plugin options use their documented defaults; existing supported values are retained.',
    externalState:
      'Complete or cancel pending remote interactions before migration; their live state is not transferred.',
    pluginVersion:
      'Install the required plugin version, then refresh. Older versions are not compatible with this migration.',
    schemaChanged:
      'The installed runner configuration does not match the migration target. Check the plugin version and refresh.',
    runnerExcluded:
      'This pipeline excludes the required runner plugin. Update its extension settings first.',
    boxScope:
      'A custom Box session template cannot be migrated safely. Remove it or review the isolation requirements first.',
    pendingInteraction:
      'A conversation is waiting for input. Complete or cancel it before migration.',
  },
  title: 'Pipeline migration',
  description:
    'Nothing changes until you select pipelines and explicitly confirm. Migration preserves pipeline identity and unrelated settings.',
  detected: '{{count}} pipelines need migration review.',
  review: 'Review migration',
  readOnly: 'Only workspace managers can migrate pipelines.',
  previewError: 'Preview unavailable. Refresh to check again.',
  submitting: 'Submitting selected pipelines…',
  running:
    'Migration is running. Closing this dialog does not cancel the task.',
  finished: 'Task finished. Check each pipeline result below.',
  failed: 'Task failed. Check each pipeline result below.',
  lost: 'Task observation lost. Its outcome is unknown; refresh the preview before any further action.',
  requestError:
    'Request not completed. Refresh the preview before selecting again.',
  warningFallback: 'Review this setting before migration.',
  blockerFallback:
    'This setting or runtime condition cannot be migrated safely. Resolve it and refresh the preview.',
  changedFields: 'Changed fields',
  activationHint:
    'Configuration was saved, but activation is pending. Ask a workspace administrator to check runtime availability, then refresh. Do not rerun migration blindly.',
  pluginHint:
    'Install or enable the required runner plugin through Extensions / Extension Market. Review your workspace extension quota there; this assistant never installs plugins. Return here and refresh the preview.',
  extensions: 'Open Extensions',
  results: 'Per-pipeline results',
  selection: '{{count}} selected (maximum 50)',
  confirm: 'I confirm migration of the selected pipelines.',
  refresh: 'Refresh preview',
  execute: 'Migrate selected',
  legacyGate:
    'Legacy configuration is read-only until migration. Save and debug are unavailable to prevent implicit conversion.',
  states: {
    ready: 'Ready',
    needs_plugin: 'Plugin required',
    blocked: 'Blocked',
    already_current: 'Already current',
    not_legacy: 'Not legacy',
    activation_pending: 'Activation pending',
    pending: 'Pending',
    migrated: 'Migrated',
    stale: 'Stale preview',
    failed: 'Failed',
  },
};
